---
title: "Comparando mecanismos para jukebox sociais"
output:
    html_document:
    df_print: paged
theme: sandstone
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(broom)
theme_set(theme_bw())

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5)

```

```{r read}
dados = read_csv(here::here("data/satisfacoes.csv"), 
                 col_types = "cdcc") 

comparacao1 = dados %>% 
    filter(scenario %in% c("combined", "up/downvoting"))

glimpse(comparacao1)
```


```{r}
theta_chapeu = {
    satisfacoes = comparacao1 %>% 
        group_by(scenario) %>% 
        summarise(satisfacao = mean(satisfaction), 
                  .groups = "drop") 
    
    like = satisfacoes %>% filter(scenario == "up/downvoting") %>% pull(satisfacao)
    baseline = satisfacoes %>% filter(scenario == "combined") %>% pull(satisfacao)
    
    like - baseline
}

theta_chapeu
```


```{r}
theta_emb = function(d) {
  satisfacoes = d %>%
    mutate(scenario_embaralhado = sample(scenario, n())) %>%
    group_by(scenario_embaralhado) %>%
    summarise(satisfacao = mean(satisfaction),
              .groups = "drop")
  
  like = satisfacoes %>% filter(scenario_embaralhado == "up/downvoting") %>% pull(satisfacao)
  baseline = satisfacoes %>% filter(scenario_embaralhado == "combined") %>% pull(satisfacao)
  
  like - baseline
}

theta_emb(comparacao1)
```

```{r}
diffs = replicate(10000, {theta_emb(comparacao1)})

tibble(diferenca = diffs) %>%
  ggplot(aes(x = diferenca)) +
  # geom_histogram(binwidth = .1,
  #                fill = "white",
  #                color = "darkgreen") +
  geom_density(fill = "white", color = "darkgreen") +
  geom_vline(xintercept = theta_chapeu,
             color = "orange") +
  geom_vline(xintercept = -theta_chapeu,
             color = "orange")

sum(abs(diffs) >= abs(theta_chapeu)) / length(diffs)
```

A alternativa up/down produz mais satisfação na média que a alternativa combined (F = 44.12, n = 23, p = .03). 

diferença de médias: t-teste

```{r}
t.test(comparacao1 %>% filter(scenario == "up/downvoting") %>% pull(satisfaction), 
       comparacao1 %>% filter(scenario == "combined") %>% pull(satisfaction)) %>% 
  tidy()
```
Diferença de medianas: Teste de Wilcoxon (ou Mann-Whithney)

```{r}
wilcox.test(
  comparacao1 %>% filter(scenario == "up/downvoting") %>% pull(satisfaction),
  comparacao1 %>% filter(scenario == "combined") %>% pull(satisfaction)
) %>% tidy()
```

