---
title: "Comparando mecanismos para jukebox sociais"
output:
    html_document:
    df_print: paged
theme: sandstone
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
theme_set(theme_bw())

library(boot)
library(broom)

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5)

```

```{r read}
dados = read_csv(here::here("data/satisfacoes.csv"), 
                 col_types = "cdcc") 

dados = dados %>% 
    filter(scenario != "like/dislike")

glimpse(dados)
```

```{r}
dados_wide = dados %>% 
    pivot_wider(names_from = "scenario", values_from = satisfaction) 

dados_wide = dados_wide %>% 
    mutate(
        combined_baseline = combined - baseline, 
        updown_baseline = `up/downvoting` - baseline
    ) 
```



```{r}
theta <- function(d, i) {
    d[i] %>% 
        mean(na.rm = T)
}

theta(dados_wide$combined_baseline, 1:NROW(dados_wide))

theta(dados_wide$updown_baseline, 1:NROW(dados_wide))
```

```{r}
ci_combined = boot(data = dados_wide$combined_baseline,
                   statistic = theta,
                   R = 2000) %>%
    tidy(conf.level = .95,
         conf.method = "bca",
         conf.int = TRUE)

ci_combined

ci_updown = boot(data = dados_wide$updown_baseline,
                   statistic = theta,
                   R = 2000) %>%
    tidy(conf.level = .95,
         conf.method = "bca",
         conf.int = TRUE)

ci_updown
```

